/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resturant_s;
//Importing Libraries
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Talha
 */
public class EmpEdit extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    //Constructor
    public EmpEdit() {
        initComponents();
         tableupdate();
         this.setLocationRelativeTo(null);
    }   
    
    //Databse Connection Variables
    Connection con;
    PreparedStatement pst; 
    ResultSet rs;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    //Table Update Method
    public void tableupdate(){
        int c;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://E:\\EmpDatabase.accdb");
            pst = con.prepareStatement("select * from Record");
            rs = pst.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel)jTable1.getModel();
            dft.setRowCount(0);
            
            while (rs.next())
            {
                Vector v2 = new Vector();
                for(int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("empname"));
                    v2.add(rs.getString("phone"));
                    v2.add(rs.getString("salary"));
                    
                }
                dft.addRow(v2);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmpEdit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EmpEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxtempname = new javax.swing.JTextField();
        jtxtempphone = new javax.swing.JTextField();
        jtxtemppay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnedit = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registered Employees");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 493, -1));

        jtxtempname.setEditable(false);
        jtxtempname.setBackground(new java.awt.Color(152, 32, 76));
        jtxtempname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtempname.setBorder(null);
        jtxtempname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 12, -1, 23));

        jtxtempphone.setBackground(new java.awt.Color(240, 240, 240));
        jtxtempphone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtempphone.setForeground(new java.awt.Color(0, 102, 102));
        jtxtempphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtempphone.setBorder(null);
        jtxtempphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempphoneActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtempphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 110, 30));

        jtxtemppay.setBackground(new java.awt.Color(240, 240, 240));
        jtxtemppay.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtemppay.setForeground(new java.awt.Color(0, 102, 102));
        jtxtemppay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtemppay.setBorder(null);
        jtxtemppay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtemppayActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtemppay, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Employee Name", "Phone", "Pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 221));

        jbtnedit.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jbtnedit.setForeground(new java.awt.Color(0, 102, 102));
        jbtnedit.setText("Delete\n");
        jbtnedit.setBorder(null);
        jbtnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 120, 40));

        jbtnadd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jbtnadd.setForeground(new java.awt.Color(0, 102, 102));
        jbtnadd.setText("Edit");
        jbtnadd.setBorder(null);
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 130, 40));

        jbtnback.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jbtnback.setForeground(new java.awt.Color(0, 102, 102));
        jbtnback.setText("Back to menu ");
        jbtnback.setBorder(null);
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 170, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pay");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 90, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Phone");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 90, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-990, -10, 1740, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Open Employee Form Buttom
    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        Employee e = new Employee();
        e.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jbtnbackActionPerformed
//Add Another Row to table
    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedIndex= jTable1.getSelectedRow();

        int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());

        String name , phone , Salary;
        name = jtxtempname.getText();
        phone = jtxtempphone.getText();
        Salary = jtxtemppay.getText();

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://E:\\EmpDatabase.accdb");

            pst = con.prepareStatement("update Record set empname=?, phone=?, salary=? where id=?");
            pst.setString(1, name);
            pst.setString(2, phone);
            pst.setString(3, Salary);
            pst.setInt(4, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Updated!");
            jtxtempname.setText("");
            jtxtempphone.setText("");
            jtxtemppay.setText("");
            jtxtempname.requestFocus();

            tableupdate();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmpEdit.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);

        } catch (SQLException ex) {
            Logger.getLogger(EmpEdit.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        }

    }//GEN-LAST:event_jbtnaddActionPerformed
//Edit Employee Details
    private void jbtneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditActionPerformed

        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedIndex= jTable1.getSelectedRow();

        int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
        int dialogresult= JOptionPane.showConfirmDialog(null, "Do you want to delete this record?","Warning!",JOptionPane.YES_NO_OPTION);
        if(dialogresult == JOptionPane.YES_NO_OPTION)
        {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://E:\\EmpDatabase.accdb");

                pst = con.prepareStatement("delete from Record  where id=?");

                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Record Deleted!");
                tableupdate();
                jtxtempname.setText("");
                jtxtempphone.setText("");
                jtxtemppay.setText("");
                jtxtempname.requestFocus();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EmpEdit.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(EmpEdit.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtneditActionPerformed
//Get Employee data when row clicked
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedIndex= jTable1.getSelectedRow();
        jtxtempname.setText(model.getValueAt(selectedIndex, 1).toString());
        jtxtempphone.setText(model.getValueAt(selectedIndex, 2).toString());
        jtxtemppay.setText(model.getValueAt(selectedIndex, 3).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jtxtempnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempnameActionPerformed

    private void jtxtempphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempphoneActionPerformed

    private void jtxtemppayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtemppayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtemppayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnedit;
    private javax.swing.JTextField jtxtempname;
    private javax.swing.JTextField jtxtemppay;
    private javax.swing.JTextField jtxtempphone;
    // End of variables declaration//GEN-END:variables
}
