/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resturant_s;
//Importing Libraries
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Talha
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    //Constructor 
    public Employee() {
        initComponents();
         tableupdate();
    }   
    
    //Access Driver Variables 
    Connection con;
    PreparedStatement pst; 
    ResultSet rs;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    //Connecting to JDBC For Access Database 
    public void tableupdate(){
        int c;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://E:\\EmpDatabase.accdb");
            pst = con.prepareStatement("select * from Record");
            rs = pst.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel)jTable1.getModel();
            dft.setRowCount(0);
    //Updating  Information to Table 
            while (rs.next())
            {
                Vector v2 = new Vector();
                for(int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("empname"));
                    v2.add(rs.getString("phone"));
                    v2.add(rs.getString("salary"));
                    
                }
                dft.addRow(v2);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtempname = new javax.swing.JTextField();
        jtxtempphone = new javax.swing.JTextField();
        jtxtemppay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnedit = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 460));
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Phone");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pay ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registered Employees");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 690, 60));

        jtxtempname.setBackground(new java.awt.Color(240, 240, 240));
        jtxtempname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jtxtempname.setForeground(new java.awt.Color(0, 102, 102));
        jtxtempname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtempname.setBorder(null);
        jtxtempname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, 30));

        jtxtempphone.setBackground(new java.awt.Color(240, 240, 240));
        jtxtempphone.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jtxtempphone.setForeground(new java.awt.Color(0, 102, 102));
        jtxtempphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtempphone.setBorder(null);
        jPanel1.add(jtxtempphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 200, 30));

        jtxtemppay.setBackground(new java.awt.Color(240, 240, 240));
        jtxtemppay.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jtxtemppay.setForeground(new java.awt.Color(0, 102, 102));
        jtxtemppay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jtxtemppay, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 190, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Employee Name", "Phone", "Pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 430, 200));

        jbtnedit.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jbtnedit.setForeground(new java.awt.Color(0, 102, 102));
        jbtnedit.setText("Edit");
        jbtnedit.setBorder(null);
        jbtnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 160, 30));

        jbtnadd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jbtnadd.setForeground(new java.awt.Color(0, 102, 102));
        jbtnadd.setText("Add");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 170, 30));

        jbtnback.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jbtnback.setForeground(new java.awt.Color(0, 102, 102));
        jbtnback.setText("Sign Out");
        jbtnback.setBorder(null);
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 160, 30));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Back To Menu ");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 600, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-990, -10, 1740, 600));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Adding Data to Table via Add Button 
    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed

      String name , phone , Salary;
      name = jtxtempname.getText();
      phone = jtxtempphone.getText();
      Salary = jtxtemppay.getText();
      
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://E:\\EmpDatabase.accdb");
            
            pst = con.prepareStatement("insert into Record(empname,phone,salary)values(?,?,?) ");
            pst.setString(1, name);
            pst.setString(2, phone);
            pst.setString(3, Salary);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Added!");
            jtxtempname.setText("");
            jtxtempphone.setText("");
            jtxtemppay.setText("");
            jtxtempname.requestFocus();

            tableupdate();
            
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this,ex);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this,ex);
        }
      
      
      
      
    }//GEN-LAST:event_jbtnaddActionPerformed
//Button to go to Edit Form 
    private void jbtneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditActionPerformed
        
        EmpEdit edit = new EmpEdit();
        edit.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jbtneditActionPerformed
//Button to go back to login screen 
    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
       Login l = new Login();
        l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jtxtempnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Menu m = new Menu();
    m.setVisible(true);
    setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnedit;
    private javax.swing.JTextField jtxtempname;
    private javax.swing.JTextField jtxtemppay;
    private javax.swing.JTextField jtxtempphone;
    // End of variables declaration//GEN-END:variables
}
