/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resturant_s;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Talha
 */
public class Inventory_Table extends javax.swing.JFrame {

    /**
     * Creates new form Inventory_Table
     */
    public Inventory_Table() {
        initComponents();
    }
   //Access Driver Variables 
    Connection con;
    PreparedStatement pst; 
    ResultSet rs;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOpen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonOpen1 = new javax.swing.JButton();
        jButtonOpen2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButtonOpen.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonOpen.setForeground(new java.awt.Color(0, 102, 102));
        jButtonOpen.setText("Update Inventory");
        jButtonOpen.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Employee Name", "Rebull", "Milk", "Tea ", "Coffee", "Soda", "Fish", "Rice", "Chicken", "Pizza ", "Beef Patties"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 960, 200));

        jButtonOpen1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonOpen1.setForeground(new java.awt.Color(0, 102, 102));
        jButtonOpen1.setText("Update Inventory");
        jButtonOpen1.setBorder(null);
        jButtonOpen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpen1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOpen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 36));

        jButtonOpen2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonOpen2.setForeground(new java.awt.Color(0, 102, 102));
        jButtonOpen2.setText("Back to Menu");
        jButtonOpen2.setBorder(null);
        jButtonOpen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpen2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOpen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 960, 36));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Update Ineventory button 
    private void jButtonOpen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpen1ActionPerformed
        Update_Inventory ut = new Update_Inventory();
        ut.setVisible(true);
        setVisible(false);
        ut.pack();
        ut.setLocationRelativeTo(null);
        ut.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        tableUpdate();
    }//GEN-LAST:event_jButtonOpen1ActionPerformed

    public void tableUpdate(){
        int c;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://E:\\EmpDatabase.accdb");
            pst = con.prepareStatement("select * from Inventory");
            rs = pst.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel)jTable1.getModel();
            dft.setRowCount(0);
    //Updating  Information to Table 
            while (rs.next())
            {
                Vector v2 = new Vector();
                for(int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("Date"));
                    v2.add(rs.getString("Name"));
                    v2.add(rs.getString("redbull"));
                    v2.add(rs.getString("milk"));
                    v2.add(rs.getString("tea"));
                    v2.add(rs.getString("coffee"));
                    v2.add(rs.getString("soda"));
                    v2.add(rs.getString("fish"));
                    v2.add(rs.getString("rice"));
                    v2.add(rs.getString("chicken"));
                    v2.add(rs.getString("pizza"));
                    v2.add(rs.getString("beef"));
                }
                dft.addRow(v2);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    private void jButtonOpen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpen2ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonOpen2ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonOpen1;
    private javax.swing.JButton jButtonOpen2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
