/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resturant_s;


//Libraries Import
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.Timer;




/**
 *
 * @author Talha
 */


public class Resturants extends javax.swing.JFrame {

    
    /**
     * Creates new form Restaurants
     */
    
    //Ignore Spelling Mistake:)
    public Resturants() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jtxtFish = new javax.swing.JTextField();
        jtxtRice = new javax.swing.JTextField();
        jtxtPizza = new javax.swing.JTextField();
        jtxtBeef = new javax.swing.JTextField();
        jtxtChicken = new javax.swing.JTextField();
        jlblTea1 = new javax.swing.JLabel();
        jlblSoda1 = new javax.swing.JLabel();
        jlblShake1 = new javax.swing.JLabel();
        jlblTax4 = new javax.swing.JLabel();
        jlblCoffee1 = new javax.swing.JLabel();
        jlblMint1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jtxtTotalCost = new javax.swing.JTextField();
        jtxtCostMeal = new javax.swing.JTextField();
        jlblTax1 = new javax.swing.JLabel();
        jlblTotal1 = new javax.swing.JLabel();
        jlblSubTotal1 = new javax.swing.JLabel();
        jtxtCostDrinks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jlblShake = new javax.swing.JLabel();
        jlblMint = new javax.swing.JLabel();
        jtxtSoda = new javax.swing.JTextField();
        jtxtShake = new javax.swing.JTextField();
        jlblTea = new javax.swing.JLabel();
        jlblCoffee = new javax.swing.JLabel();
        jlblSoda = new javax.swing.JLabel();
        jtxtRed = new javax.swing.JTextField();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtTea = new javax.swing.JTextField();
        jlblTax3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbtnprintreceipt = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(566, 190));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtFish.setBackground(new java.awt.Color(240, 240, 240));
        jtxtFish.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtFish.setForeground(new java.awt.Color(0, 102, 102));
        jtxtFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFish.setBorder(null);
        jPanel2.add(jtxtFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 150, 30));

        jtxtRice.setBackground(new java.awt.Color(240, 240, 240));
        jtxtRice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtRice.setForeground(new java.awt.Color(0, 102, 102));
        jtxtRice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRice.setBorder(null);
        jPanel2.add(jtxtRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 88, 150, 30));

        jtxtPizza.setBackground(new java.awt.Color(240, 240, 240));
        jtxtPizza.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtPizza.setForeground(new java.awt.Color(0, 102, 102));
        jtxtPizza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPizza.setBorder(null);
        jPanel2.add(jtxtPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 138, 150, 30));

        jtxtBeef.setBackground(new java.awt.Color(240, 240, 240));
        jtxtBeef.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtBeef.setForeground(new java.awt.Color(0, 102, 102));
        jtxtBeef.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBeef.setBorder(null);
        jPanel2.add(jtxtBeef, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 188, 150, 30));

        jtxtChicken.setBackground(new java.awt.Color(240, 240, 240));
        jtxtChicken.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtChicken.setForeground(new java.awt.Color(0, 102, 102));
        jtxtChicken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChicken.setBorder(null);
        jtxtChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtChicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 150, 30));

        jlblTea1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblTea1.setForeground(new java.awt.Color(240, 240, 240));
        jlblTea1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTea1.setText("Fish Platter");
        jPanel2.add(jlblTea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jlblSoda1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblSoda1.setForeground(new java.awt.Color(240, 240, 240));
        jlblSoda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSoda1.setText("Signature Pizza");
        jPanel2.add(jlblSoda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jlblShake1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblShake1.setForeground(new java.awt.Color(240, 240, 240));
        jlblShake1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblShake1.setText("Signature Beef Burger");
        jPanel2.add(jlblShake1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jlblTax4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jlblTax4.setForeground(new java.awt.Color(240, 240, 240));
        jlblTax4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTax4.setText("Meals");
        jPanel2.add(jlblTax4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 12, 100, -1));

        jlblCoffee1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblCoffee1.setForeground(new java.awt.Color(240, 240, 240));
        jlblCoffee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCoffee1.setText("Chicken Rice");
        jPanel2.add(jlblCoffee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jlblMint1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblMint1.setForeground(new java.awt.Color(240, 240, 240));
        jlblMint1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMint1.setText("Signature Chicken Burger");
        jPanel2.add(jlblMint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 244, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 72, 150, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 500, 280));

        jPanel4.setPreferredSize(new java.awt.Dimension(490, 170));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTotalCost.setBackground(new java.awt.Color(240, 240, 240));
        jtxtTotalCost.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtTotalCost.setForeground(new java.awt.Color(0, 102, 102));
        jtxtTotalCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotalCost.setBorder(null);
        jPanel4.add(jtxtTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 150, 30));

        jtxtCostMeal.setBackground(new java.awt.Color(240, 240, 240));
        jtxtCostMeal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtCostMeal.setForeground(new java.awt.Color(0, 102, 102));
        jtxtCostMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCostMeal.setBorder(null);
        jPanel4.add(jtxtCostMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 150, 30));

        jlblTax1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblTax1.setForeground(new java.awt.Color(240, 240, 240));
        jlblTax1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTax1.setText("Meal Cost");
        jPanel4.add(jlblTax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jlblTotal1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblTotal1.setForeground(new java.awt.Color(240, 240, 240));
        jlblTotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotal1.setText("Total Cost of Items");
        jPanel4.add(jlblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jlblSubTotal1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblSubTotal1.setForeground(new java.awt.Color(240, 240, 240));
        jlblSubTotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSubTotal1.setText("Drinks Cost");
        jPanel4.add(jlblSubTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 114, -1));

        jtxtCostDrinks.setBackground(new java.awt.Color(240, 240, 240));
        jtxtCostDrinks.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtCostDrinks.setForeground(new java.awt.Color(0, 102, 102));
        jtxtCostDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCostDrinks.setBorder(null);
        jPanel4.add(jtxtCostDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 150, 30));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 16, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, -1, 510));

        jPanel6.setMinimumSize(new java.awt.Dimension(800, 533));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblShake.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblShake.setForeground(new java.awt.Color(240, 240, 240));
        jlblShake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblShake.setText("Chocolate Shake");
        jPanel6.add(jlblShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 161, -1));

        jlblMint.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblMint.setForeground(new java.awt.Color(240, 240, 240));
        jlblMint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMint.setText("RedBull");
        jPanel6.add(jlblMint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 161, -1));

        jtxtSoda.setBackground(new java.awt.Color(240, 240, 240));
        jtxtSoda.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtSoda.setForeground(new java.awt.Color(0, 102, 102));
        jtxtSoda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSoda.setBorder(null);
        jPanel6.add(jtxtSoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 150, 30));

        jtxtShake.setBackground(new java.awt.Color(240, 240, 240));
        jtxtShake.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtShake.setForeground(new java.awt.Color(0, 102, 102));
        jtxtShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtShake.setBorder(null);
        jtxtShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtShakeActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 150, 30));

        jlblTea.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblTea.setForeground(new java.awt.Color(240, 240, 240));
        jlblTea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTea.setText("Tea");
        jPanel6.add(jlblTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        jlblCoffee.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblCoffee.setForeground(new java.awt.Color(240, 240, 240));
        jlblCoffee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCoffee.setText("Coffee");
        jPanel6.add(jlblCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        jlblSoda.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblSoda.setForeground(new java.awt.Color(240, 240, 240));
        jlblSoda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSoda.setText("Soda");
        jPanel6.add(jlblSoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, -1));

        jtxtRed.setBackground(new java.awt.Color(240, 240, 240));
        jtxtRed.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtRed.setForeground(new java.awt.Color(0, 102, 102));
        jtxtRed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRed.setBorder(null);
        jPanel6.add(jtxtRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 150, 30));

        jtxtCoffee.setBackground(new java.awt.Color(240, 240, 240));
        jtxtCoffee.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtCoffee.setForeground(new java.awt.Color(0, 102, 102));
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setBorder(null);
        jtxtCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCoffeeActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 150, 30));

        jtxtTea.setBackground(new java.awt.Color(240, 240, 240));
        jtxtTea.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtTea.setForeground(new java.awt.Color(0, 102, 102));
        jtxtTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTea.setBorder(null);
        jPanel6.add(jtxtTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 46, 150, 30));

        jlblTax3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jlblTax3.setForeground(new java.awt.Color(240, 240, 240));
        jlblTax3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTax3.setText("Drinks");
        jPanel6.add(jlblTax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 12, 100, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 480, 280));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnprintreceipt.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jbtnprintreceipt.setForeground(new java.awt.Color(0, 102, 102));
        jbtnprintreceipt.setText("Print Receipt");
        jbtnprintreceipt.setBorder(null);
        jbtnprintreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnprintreceiptActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnprintreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 190, 40));

        jButtonExit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(0, 102, 102));
        jButtonExit.setText("Exit");
        jButtonExit.setBorder(null);
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 200, 40));

        jbtnReset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(0, 102, 102));
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(null);
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 170, 40));

        jbtnTotal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jbtnTotal.setForeground(new java.awt.Color(0, 102, 102));
        jbtnTotal.setText("Total");
        jbtnTotal.setBorder(null);
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 40));

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Become a Member ");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 180, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1440, 80));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1370, 80));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTax.setBackground(new java.awt.Color(240, 240, 240));
        jtxtTax.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtTax.setForeground(new java.awt.Color(0, 102, 102));
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTax.setBorder(null);
        jPanel8.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 150, 30));

        jtxtSubTotal.setBackground(new java.awt.Color(240, 240, 240));
        jtxtSubTotal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtSubTotal.setForeground(new java.awt.Color(0, 102, 102));
        jtxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSubTotal.setBorder(null);
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel8.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 150, 30));

        jtxtTotal.setBackground(new java.awt.Color(240, 240, 240));
        jtxtTotal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtTotal.setForeground(new java.awt.Color(0, 102, 102));
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotal.setBorder(null);
        jPanel8.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 150, 30));

        jlblTax.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblTax.setForeground(new java.awt.Color(240, 240, 240));
        jlblTax.setText("Tax");
        jPanel8.add(jlblTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, -1));

        jlblSubTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblSubTotal.setForeground(new java.awt.Color(240, 240, 240));
        jlblSubTotal.setText("Sub Total");
        jPanel8.add(jlblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        jlblTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlblTotal.setForeground(new java.awt.Color(240, 240, 240));
        jlblTotal.setText("Total");
        jPanel8.add(jlblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 180));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 490, 170));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 100, 1430, 680));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 55)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Restaurant Management System");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -1, 1530, 100));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1440, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      Member m = new Member();
      m.setVisible(true);
      setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    //Working For The Total Button 
    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        SubClass itemCost = new SubClass();

        double iTax , iSubTotal , iTotal;
        
//Item Cost
        itemCost.FishPlatter = itemCost.pFishPlatter * Double.parseDouble(jtxtFish.getText());
        itemCost.ChickenRice = itemCost.pChickenRice * Double.parseDouble(jtxtRice.getText());
        itemCost.SignaturePizza = itemCost.pSignaturePizza * Double.parseDouble(jtxtPizza.getText());
        itemCost.SignatureBeefBurger = itemCost.pSignatureBeefBurger * Double.parseDouble(jtxtBeef.getText());
        itemCost.SignatureChickenBurger = itemCost.pSignatureChickenBurger * Double.parseDouble(jtxtChicken.getText());

        itemCost.Tea = itemCost.pTea * Double.parseDouble(jtxtTea.getText());
        itemCost.Coffee = itemCost.pCoffee * Double.parseDouble(jtxtCoffee.getText());
        itemCost.Soda = itemCost.pSoda * Double.parseDouble(jtxtSoda.getText());
        itemCost.ChocolateMilkshake = itemCost.pChocolateMilkshake * Double.parseDouble(jtxtShake.getText());
        itemCost.RedBull= itemCost.pRedBull * Double.parseDouble(jtxtRed.getText());
        
//Total Calculation 
        iSubTotal = itemCost.GetAmount();
        iTax = itemCost.FindTax(iSubTotal);
        iTotal = iSubTotal + iTax;

        String SubTotal =  String.format ("PKR%.2f" , iSubTotal);
        jtxtSubTotal.setText(SubTotal);

        String Tax =  String.format ("PKR%.2f" , iTax);
        jtxtTax.setText(Tax);

        String Total =  String.format ("PKR%.2f" , iTotal);
        jtxtTotal.setText(Total);

        String Meal = String.format ("PKR%.2f", itemCost.Meals);
        jtxtCostMeal.setText(Meal);

        String Drink = String.format("PKR%.2f", itemCost.Drinks);
        jtxtCostDrinks.setText(Drink);

        String TotalCost = String.format("PKR%.2f", itemCost.TotalofMD);
        jtxtTotalCost.setText(TotalCost);
    }//GEN-LAST:event_jbtnTotalActionPerformed
//Working For Reset Button 
    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField cleartext=null;
        for (Component d:jPanel8.getComponents()){
            if(d.getClass().toString().contains("javax.swing.JTextField"))
            {cleartext=(JTextField )d;
                cleartext.setText("");
            }
        }
        for (Component b:jPanel4.getComponents()){
            if(b.getClass().toString().contains("javax.swing.JTextField"))
            {cleartext=(JTextField )b;
                cleartext.setText("");
            }
        }
        for (Component a:jPanel6.getComponents()){
            if(a.getClass().toString().contains("javax.swing.JTextField"))
            {cleartext=(JTextField )a;
                cleartext.setText("0");
            }
        }

        for (Component c:jPanel2.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {cleartext=(JTextField )c;
                cleartext.setText("0");
            }
        }jtxtReceipt.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed
//Working For Exit Button 
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        SubClass iExit = new SubClass();
        iExit.iExitSystem();
    }//GEN-LAST:event_jButtonExitActionPerformed
//Working For Receipt Button 
    private void jbtnprintreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnprintreceiptActionPerformed
//Random Number Generation 
        int refs=1325+ (int) (Math.random()*4238);
//Time & Date 
        Calendar timer =Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate=new SimpleDateFormat("dd:MM:yyyy");
        Tdate.format(timer.getTime());
//Text Output For Receipt 
        jtxtReceipt.append("\tResturant Management System:\n" +
            "Reference:\t\t\t" + refs +
            "\n=============================\n" +

            "Meals:\t\t" + jtxtCostMeal.getText() + "\n\n"+
            "Drinks:\t\t" + jtxtCostDrinks.getText() + "\n\n"+
            "Cost of Items:\t" + jtxtTotalCost.getText() + "\n\n"+
            "====================================" +  "\n\n"+
            "Tax:\t\t" + jtxtTax.getText()  +  "\n\n"+
            "Sub Total:\t\t" + jtxtSubTotal.getText()  +  "\n\n"+
            "Total:\t\t" + jtxtTotal.getText()  +  "\n" +
            "====================================" +
            "\nDate: " + Tdate.format(timer.getTime()) +
            "\tTime: " +tTime.format(timer.getTime()) +
            "\n\n\t Thankyou!");
    }//GEN-LAST:event_jbtnprintreceiptActionPerformed

    private void jtxtShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtShakeActionPerformed

    private void jtxtChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCoffeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resturants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resturants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resturants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resturants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resturants();
                new Resturants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JButton jbtnprintreceipt;
    private javax.swing.JLabel jlblCoffee;
    private javax.swing.JLabel jlblCoffee1;
    private javax.swing.JLabel jlblMint;
    private javax.swing.JLabel jlblMint1;
    private javax.swing.JLabel jlblShake;
    private javax.swing.JLabel jlblShake1;
    private javax.swing.JLabel jlblSoda;
    private javax.swing.JLabel jlblSoda1;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblSubTotal1;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTax1;
    private javax.swing.JLabel jlblTax3;
    private javax.swing.JLabel jlblTax4;
    private javax.swing.JLabel jlblTea;
    private javax.swing.JLabel jlblTea1;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotal1;
    private javax.swing.JTextField jtxtBeef;
    private javax.swing.JTextField jtxtChicken;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtCostDrinks;
    private javax.swing.JTextField jtxtCostMeal;
    private javax.swing.JTextField jtxtFish;
    private javax.swing.JTextField jtxtPizza;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtRed;
    private javax.swing.JTextField jtxtRice;
    private javax.swing.JTextField jtxtShake;
    private javax.swing.JTextField jtxtSoda;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTea;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtTotalCost;
    // End of variables declaration//GEN-END:variables
}
