/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resturant_s;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Talha
 */
public class Update_Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Update_Inventory
     */
    public Update_Inventory() {
        initComponents();
    }
  //ddatabase varibles
      Connection con;
      PreparedStatement pst; 
       ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldl = new javax.swing.JTextField();
        jTextFieldb = new javax.swing.JTextField();
        jTextFieldc = new javax.swing.JTextField();
        jTextFieldd = new javax.swing.JTextField();
        jTextFielde = new javax.swing.JTextField();
        jTextFieldf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFielda = new javax.swing.JTextField();
        jTextFieldg = new javax.swing.JTextField();
        jTextFieldh = new javax.swing.JTextField();
        jTextFieldi = new javax.swing.JTextField();
        jTextFieldj = new javax.swing.JTextField();
        jTextFieldk = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Add To Inventory");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 950, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Beef ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Employee Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Red Bull");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Milk");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tea");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Coffee");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Soda");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fish");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Rice");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Chicken");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Pizza");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jTextFieldl.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldl.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldl.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldl.setBorder(null);
        jTextFieldl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 270, 30));

        jTextFieldb.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldb.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldb.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldb.setBorder(null);
        jTextFieldb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 270, 30));

        jTextFieldc.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldc.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldc.setBorder(null);
        jTextFieldc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 270, 30));

        jTextFieldd.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldd.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldd.setBorder(null);
        jTextFieldd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 270, 30));

        jTextFielde.setBackground(new java.awt.Color(240, 240, 240));
        jTextFielde.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFielde.setForeground(new java.awt.Color(0, 102, 102));
        jTextFielde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielde.setBorder(null);
        jTextFielde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielde, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 270, 30));

        jTextFieldf.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldf.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldf.setBorder(null);
        jTextFieldf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldfActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 270, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 22, 120, 300));

        jTextFielda.setBackground(new java.awt.Color(240, 240, 240));
        jTextFielda.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFielda.setForeground(new java.awt.Color(0, 102, 102));
        jTextFielda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielda.setBorder(null);
        jTextFielda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 270, 30));

        jTextFieldg.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldg.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldg.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldg.setBorder(null);
        jTextFieldg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldg, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 270, 30));

        jTextFieldh.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldh.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldh.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldh.setBorder(null);
        jTextFieldh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldhActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 270, 30));

        jTextFieldi.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldi.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldi.setBorder(null);
        jTextFieldi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldiActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 270, 30));

        jTextFieldj.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldj.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldj.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldj.setBorder(null);
        jTextFieldj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldjActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldj, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 270, 30));

        jTextFieldk.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldk.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldk.setForeground(new java.awt.Color(0, 102, 102));
        jTextFieldk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldk.setBorder(null);
        jTextFieldk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldkActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldk, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 270, 30));

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Back to Table");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 950, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resturant_s/24636.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlActionPerformed

    private void jTextFieldbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbActionPerformed

    private void jTextFieldcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcActionPerformed

    private void jTextFielddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddActionPerformed

    private void jTextFieldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldeActionPerformed

    private void jTextFieldfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldfActionPerformed

    private void jTextFieldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldaActionPerformed

    private void jTextFieldgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgActionPerformed

    private void jTextFieldhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldhActionPerformed

    private void jTextFieldiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldiActionPerformed

    private void jTextFieldjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldjActionPerformed

    private void jTextFieldkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldkActionPerformed

//Add Inventory Button 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String date , name , redbull , milk , tea , coffee, soda , fish , rice ,chicken, pizza , beef;
      date = jTextFielda.getText();
     name = jTextFieldb.getText();
      redbull = jTextFieldc.getText();
       milk = jTextFieldd.getText();
        tea = jTextFielde.getText();
         coffee =jTextFieldf.getText();
          soda = jTextFieldg.getText();
           fish = jTextFieldh.getText();
            rice = jTextFieldi.getText();
            chicken = jTextFieldj.getText();
            pizza = jTextFieldk.getText();
            beef=jTextFieldl.getText();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://E:\\EmpDatabase.accdb");
            
            pst = con.prepareStatement("insert into Inventory(date , name , redbull , milk , tea , coffee, soda , fish , rice ,chicken, pizza ,beef)values(?,?,?,?,?,?,?,?,?,?,?,?) ");
            pst.setString(1, date);
            pst.setString(2, name);
            pst.setString(3, redbull);
            pst.setString(4, milk);
            pst.setString(5, tea);
            pst.setString(6, coffee);
            pst.setString(7, soda);
            pst.setString(8, fish);
            pst.setString(9, rice);
            pst.setString(10, chicken);
            pst.setString(11, pizza);
            pst.setString(12, beef);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inventory Updated!");
            jTextFielda.setText("");
          jTextFieldb.setText("");
             jTextFieldc.setText("");
             jTextFieldd.setText("");
             jTextFielde.setText("");
             jTextFieldf.setText("");
             jTextFieldg.setText("");
             jTextFieldh.setText("");
             jTextFieldi.setText("");
             jTextFieldj.setText("");
             jTextFieldk.setText("");
             jTextFieldl.setText("");
            jTextFielda.requestFocus();
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this,ex);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this,ex);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          Inventory_Table it = new Inventory_Table();
          it.setVisible(true);
          setVisible(false);
          
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFielda;
    private javax.swing.JTextField jTextFieldb;
    private javax.swing.JTextField jTextFieldc;
    private javax.swing.JTextField jTextFieldd;
    private javax.swing.JTextField jTextFielde;
    private javax.swing.JTextField jTextFieldf;
    private javax.swing.JTextField jTextFieldg;
    private javax.swing.JTextField jTextFieldh;
    private javax.swing.JTextField jTextFieldi;
    private javax.swing.JTextField jTextFieldj;
    private javax.swing.JTextField jTextFieldk;
    private javax.swing.JTextField jTextFieldl;
    // End of variables declaration//GEN-END:variables
}
